[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-interaction --no-dev --prefer-dist"]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan optimize:clear",
  "php artisan cache:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan storage:link || true",
  "chmod -R 777 storage/",
  "chmod -R 777 public/",
  "php artisan db:wipe --force || echo 'DB wipe failed, continuing'",
  "php artisan migrate --force || echo 'Migration failed, continuing anyway'"
]

[start]
cmd = "php artisan config:clear && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}" 