[build]
builder = "nixpacks"
buildCommand = "composer install && php artisan migrate --force"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
internal_port = 8000
protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443 