[build]
builder = "nixpacks"
buildCommand = "composer install --no-interaction --no-dev --prefer-dist && php artisan config:clear && php artisan optimize:clear && php artisan cache:clear && chmod +x bootstrap-railway.sh"

[deploy]
startCommand = "bash bootstrap-railway.sh"
healthcheckPath = "/up"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[[services]]
internal_port = 8000
protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443 